services:
  web:
    build: ./app
    ports:
      - '8000:8000'
    environment:
      DB_CONNECTION: "${MYSQL_HOST}"
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_USERNAME: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      AI_API_HOST: "${AI_API_HOST}"
    links:
      - ai
      - mysql
  mysql:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_HOST: "%"
    ports:
      - '3306:3306'
  ai:
    build: ./ai
    ports:
      - '5000:5000'
