services:
  web:
    build: ./app
    ports:
      - '8000:8000'
    environment:
      DB_CONNECTION: "${MYSQL_HOST}"
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_USERNAME: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
  mysql:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_HOST: "%"
    ports:
      - '3306:3306'
